### PR TITLE
Added optional cheat mode

### PR DESCRIPTION
**Pull request by FrankSalmick**
Gives four options, one of which is right. Only works if enabled by checking a box. Defaults to disabled.

### CODE REVIEW

**Comment by FrankSalmick** [comment]
I changed it a little bit to give a hint on a click.

**Comment by AnEvenBetterName** [comment]
horrible...
fear me...
fear me...
FEAR ME...

**Comment by AnEvenBetterName** [comment]
oosk

**Comment by AnEvenBetterName** [comment]
ddiskdkso

**Pull request merged**
